// English songs playlist
const englishSongs = [
  { title: 'A Thousand Years', artist: 'Christina Perri', src: 'songs/english/A Thousand Years.mp3' },
  { title: 'Anxiety', artist: 'Doechii', src: 'songs/english/Anxiety.mp3' },
  { title: 'Attention', artist: 'Charlie Puth', src: 'songs/english/Attention.mp3' },
  { title: 'Believer', artist: 'Imagine Dragons', src: 'songs/english/Believer.mp3' },
  { title: 'Breakin Dishes', artist: 'Rihanna', src: 'songs/english/Breakin Dishes.mp3' },
  { title: 'CHANEL', artist: 'Tyla', src: 'songs/english/CHANEL.mp3' },
  { title: 'CO2', artist: 'Prateek Kuhad', src: 'songs/english/CO2.mp3' },
  { title: 'Die On This Hill', artist: 'Sienna Spiro', src: 'songs/english/Die On This Hill.mp3' },
  { title: 'Die With a Smile', artist: 'Lady Gaga, Bruno Mars', src: 'songs/english/Die With a Smile.mp3' },
  { title: 'Ends in Y', artist: 'Mimi Webb', src: 'songs/english/Ends in Y.mp3' },
  { title: 'Fix You', artist: 'Coldplay', src: 'songs/english/Fix You.mp3' },
  { title: 'FRIENDS', artist: 'Marshmello, Anne-Marie', src: 'songs/english/FRIENDS.mp3' },
  { title: 'Golden', artist: 'HUNTR/X', src: 'songs/english/Golden.mp3' },
  { title: 'I Had Some Help', artist: 'Post Malone, Morgan Wallen', src: 'songs/english/I Had Some Help.mp3' },
  { title: 'I Think They Call This Love', artist: 'Matthew Ifield', src: 'songs/english/I Think They Call This Love.mp3' },
  { title: 'I Wanna Be Yours', artist: 'Arctic Monkeys', src: 'songs/english/I Wanna Be Yours.mp3' },
  { title: 'Love Me Like You Do', artist: 'Ellie Goulding', src: 'songs/english/Love Me Like You Do.mp3' },
  { title: 'Memories', artist: 'Maroon 5', src: 'songs/english/Memories.mp3' },
  { title: 'My Love Will Never Die', artist: 'AG', src: 'songs/english/My Love Will Never Die.mp3' },
  { title: 'One and Only', artist: 'Adele', src: 'songs/english/One and Only.mp3' },
  { title: 'Ordinary', artist: 'Alex Warren', src: 'songs/english/Ordinary.mp3' },
  { title: 'Perfect', artist: 'Ed Sheeran', src: 'songs/english/Perfect.mp3' },
  { title: 'Photograph', artist: 'Ed Sheeran', src: 'songs/english/Photograph.mp3' },
  { title: 'Please Please Please', artist: 'Sabrina Carpenter', src: 'songs/english/Please Please Please.mp3' },
  { title: 'Señorita', artist: 'Shawn Mendes, Camila Cabello', src: 'songs/english/Señorita.mp3' },
  { title: 'Shape of You', artist: 'Ed Sheeran', src: 'songs/english/Shape of You.mp3' },
  { title: 'Someone Like You', artist: 'Adele', src: 'songs/english/Someone Like You.mp3' },
  { title: 'Stateside', artist: 'PinkPantheress, Zara Larsson', src: 'songs/english/Stateside.mp3' },
  { title: 'The Fate of Ophelia', artist: 'Taylor Swift', src: 'songs/english/The Fate of Ophelia.mp3' },
  { title: 'Thunder', artist: 'Imagine Dragons', src: 'songs/english/Thunder.mp3' },
  { title: 'TIT FOR TAT', artist: 'Tate McRae', src: 'songs/english/TIT FOR TAT.mp3' },
  { title: 'Too Good at Goodbyes', artist: 'Sam Smith', src: 'songs/english/Too Good at Goodbyes.mp3' },
  { title: 'Treat You Better', artist: 'Shawn Mendes', src: 'songs/english/Treat You Better.mp3' },
  { title: 'Way Down We Go', artist: 'KALEO', src: 'songs/english/Way Down We Go.mp3' },
  { title: 'Yellow', artist: 'Coldplay', src: 'songs/english/Yellow.mp3' }
];
