// Punjabi songs playlist
const punjabiSongs = [
  { title: 'Aaj Din Chadheya', artist: 'Rahat Fateh Ali Khan', src: "songs/punjabi/Aaj Din Chadheya.mp3" },
  { title: 'Bina Mahi', artist: 'Nusrat Fateh Ali Khan', src: "songs/punjabi/Bina Mahi.mp3" },
  { title: 'Dost Banke', artist: 'Rahat Fateh Ali Khan, Gurnazar', src: "songs/punjabi/Dost Banke.mp3" },
  { title: 'Ishq Di Baajiyaan', artist: 'Diljit Dosanjh', src: "songs/punjabi/Ishq Di Baajiyaan.mp3" },
  { title: 'Ishqa Ve', artist: 'Zeeshan Ali', src: "songs/punjabi/Ishqa Ve.mp3" },
  { title: 'Jhol', artist: 'Maanu, Annural Khalid', src: "songs/punjabi/Jhol.mp3" },
  { title: 'Khaab', artist: 'Akhil', src: "songs/punjabi/Khaab.mp3" },
  { title: 'Mera Mann', artist: 'Juss', src: "songs/punjabi/Mera Mann.mp3" },
  { title: 'Ranjheya Ve', artist: 'Zain Zohaib', src: "songs/punjabi/Ranjheya Ve.mp3" },
  { title: 'Roi Na', artist: 'Ninja', src: "songs/punjabi/Roi Na.mp3" },
  { title: 'Sajjan Raazi', artist: 'Satinder Sartaaj', src: "songs/punjabi/Sajjan Raazi.mp3" },
  { title: 'Sohnea', artist: 'Miss Pooja, Millind Gaba', src: "songs/punjabi/Sohnea.mp3" },
  { title: 'Suhe Bullan Waliye', artist: 'Sippy Gill, Sawan Rupowali', src: "songs/punjabi/Suhe Bullan Waliye.mp3" },
  { title: 'Udaarian (Badi Lambi Hai Kahani Mere Pyaar Di)', artist: 'Satinder Sartaaj', src: "songs/punjabi/Udaarian (Badi Lambi Hai Kahani Mere Pyaar Di).mp3" },
  { title: 'Zindagi Tere Naal', artist: 'Khan Saab, Pav Dharia', src: "songs/punjabi/Zindagi Tere Naal.mp3" },
  { title: "3 Peg", artist: "Sharry Mann", src: "songs/punjabi/3 Peg.mp3" },
  { title: "2 Raflaan", artist: "Mankirt Aulakh, Gurlez Akhtar", src: "songs/punjabi/2 Raflaan.mp3" },
  { title: "52 Bars", artist: "Karan Aujla, Ikky", src: "songs/punjabi/52 Bars.mp3" },
  { title: "8 Raflaan", artist: "Mankirt Aulakh, Gurlez Akhtar", src: "songs/punjabi/8 Raflaan.mp3" },
  { title: "Alfaaz", artist: "Hamza Malik, Zain Zohaib", src: "songs/punjabi/Alfaaz.mp3" },
  { title: "Baapu", artist: "Amrit Maan", src: "songs/punjabi/Baapu.mp3" },
  { title: "Apa Fer Milaange", artist: "Savi Kahlon", src: "songs/punjabi/Apa Fer Milaange.mp3" },
  { title: "At Peace", artist: "Karan Aujla", src: "songs/punjabi/At Peace.mp3" },
  { title: "BACHALO", artist: "Akhil, Nirmaan", src: "songs/punjabi/BACHALO.mp3" },
  { title: "Badnam", artist: "Mankirt Aulakh, DJ Flow", src: "songs/punjabi/Badnam.mp3" },
  { title: "Players", artist: "Badshah, Karan Aujla", src: "songs/punjabi/Players.mp3" },
  { title: "BAMB AAGYA", artist: "Gur Sidhu, Jasmine Sandlas", src: "songs/punjabi/BAMB AAGYA.mp3" },
  { title: "Bhabi", artist: "Mankirt Aulakh", src: "songs/punjabi/Bhabi.mp3" },
  { title: "Bitch I'm Back", artist: "Sidhu Moose Wala", src: "songs/punjabi/Bitch I'm Back.mp3" },
  { title: "Black Effect", artist: "Jordan Sandhu", src: "songs/punjabi/Black Effect.mp3" },
  { title: "Brown Munde", artist: "AP Dhillon, Gurinder Gill, Shinda Kahlon", src: "songs/punjabi/Brown Munde.mp3" },
  { title: "Brown Shortie", artist: "Sidhu Moose Wala, Sonam Bajwa", src: "songs/punjabi/Brown Shortie.mp3" },
  { title: "CALIFORNIA LOVE", artist: "Cheema Y, Gur Sidhu", src: "songs/punjabi/CALIFORNIA LOVE.mp3" },
  { title: "CHORNI", artist: "Sidhu Moose Wala, Divine", src: "songs/punjabi/CHORNI.mp3" },
  { title: "COKA", artist: "Sukh-E, Jaani", src: "songs/punjabi/COKA.mp3" },
  { title: "DAKU", artist: "Inderpal Moga, Chani Nattan", src: "songs/punjabi/DAKU.mp3" },
  { title: "Daru Badnaam", artist: "Kamal Kahlon, Param Singh", src: "songs/punjabi/Daru Badnaam.mp3" },
  { title: "DEKHYA KITE", artist: "Davy, Simar Kaur, Gur Sidhu", src: "songs/punjabi/DEKHYA KITE.mp3" },
  { title: "Diamond", artist: "Gurnam Bhullar", src: "songs/punjabi/Diamond.mp3" },
  { title: "DON", artist: "Diljit Dosanjh", src: "songs/punjabi/DON.mp3" },
  { title: "Born To Shine", artist: "Diljit Dosanjh", src: "songs/punjabi/Born To Shine.mp3" },
  { title: "CASE", artist: "Diljit Dosanjh", src: "songs/punjabi/CASE.mp3" },
  { title: "Lemonade", artist: "Diljit Dosanjh", src: "songs/punjabi/Lemonade.mp3" },
  { title: "Peaches", artist: "Diljit Dosanjh", src: "songs/punjabi/Peaches.mp3" },
  { title: "Tension", artist: "Diljit Dosanjh", src: "songs/punjabi/Tension.mp3" },
  { title: "G.O.A.T.", artist: "Diljit Dosanjh", src: "songs/punjabi/G.O.A.T..mp3" },
  { title: "Do Pall", artist: "Surinder Kaur, CoachSahb", src: "songs/punjabi/Do Pall.mp3" },
  { title: "Down To Earth", artist: "Parry Singh, Anmol Chaudhary", src: "songs/punjabi/Down To Earth.mp3" },
  { title: "Excuses", artist: "AP Dhillon, Gurinder Gill", src: "songs/punjabi/Excuses.mp3" },
  { title: "Fly Karke", artist: "Sabba, Jasmeen Akhtar", src: "songs/punjabi/Fly Karke.mp3" },
  { title: "For A Reason", artist: "Karan Aujla, Ikky", src: "songs/punjabi/For A Reason.mp3" },
  { title: "High Rated Gabru", artist: "Guru Randhawa", src: "songs/punjabi/High Rated Gabru.mp3" },
  { title: "Lahore", artist: "Guru Randhawa", src: "songs/punjabi/Lahore.mp3" },
  { title: "Made in India", artist: "Guru Randhawa", src: "songs/punjabi/Made in India.mp3" },
  { title: "GUZARISH", artist: "Satinder Sartaaj", src: "songs/punjabi/GUZARISH.mp3" },
  { title: "Haan Haige aa", artist: "Karan Aujla, Gurlez Akhtar, Rupan Bal", src: "songs/punjabi/Haan Haige aa.mp3" },
  { title: "Backbone", artist: "Harrdy Sandhu, Jaani, B Praak", src: "songs/punjabi/Backbone.mp3" },
  { title: "Bijlee Bijlee", artist: "Harrdy Sandhu, Jaani", src: "songs/punjabi/Bijlee Bijlee.mp3" },
  { title: "Kya Baat Ay", artist: "Harrdy Sandhu, Jaani, B Praak", src: "songs/punjabi/Kya Baat Ay.mp3" },
  { title: "Her", artist: "Shubh", src: "songs/punjabi/Her.mp3" },
  { title: "HINT", artist: "Karan Aujla, Rupan Bal", src: "songs/punjabi/HINT.mp3" },
  { title: "Hukam", artist: "Karan Aujla", src: "songs/punjabi/Hukam.mp3" },
  { title: "ILZAAM", artist: "Arjan Dhillon", src: "songs/punjabi/ILZAAM.mp3" },
  { title: "Oye Hoye Hoye", artist: "Jassie Gill, Simar Kaur", src: "songs/punjabi/Oye Hoye Hoye.mp3" },
  { title: "Jatt Disda", artist: "Sunanda Sharma", src: "songs/punjabi/Jatt Disda.mp3" },
  { title: "Jatt Flex", artist: "Amrit Maan", src: "songs/punjabi/Jatt Flex.mp3" },
  { title: "Jhaanjar", artist: "B Praak, Jaani, Gippy Grewal", src: "songs/punjabi/Jhaanjar.mp3" },
  { title: "FOMO", artist: "Jordan Sandhu", src: "songs/punjabi/FOMO.mp3" },
  { title: "Tere Bina Na Guzara E", artist: "Josh Brar", src: "songs/punjabi/Tere Bina Na Guzara E.mp3" },
  { title: "Judge", artist: "Mankirt Aulakh", src: "songs/punjabi/Judge.mp3" },
  { title: "Aashiq Puran", artist: "Kaka", src: "songs/punjabi/Aashiq Puran.mp3" },
  { title: "Kale Je Libaas Di", artist: "Kaka, Ginni Kapoor", src: "songs/punjabi/Kale Je Libaas Di.mp3" },
  { title: "Shape", artist: "Kaka", src: "songs/punjabi/Shape.mp3" },
  { title: "Kalli Sohni", artist: "Arjan Dhillon", src: "songs/punjabi/Kalli Sohni.mp3" },
  { title: "Chithiyaan", artist: "Karan Aujla, Rupan Bal", src: "songs/punjabi/Chithiyaan.mp3" },
  { title: "Khabbi Seat", artist: "Ammy Virk, Sweetaj Brar", src: "songs/punjabi/Khabbi Seat.mp3" },
  { title: "Kholi Darwaje Na Zubaan De Akhaan Naal Gallan Hoyi Jaan De", artist: "Artist not listed", src: "songs/punjabi/Kholi Darwaje Na Zubaan De Akhaan Naal Gallan Hoyi Jaan De.mp3" },
  { title: "Khyaal Rakhya Kar", artist: "Neha Kakkar, Rohanpreet Singh", src: "songs/punjabi/Khyaal Rakhya Kar.mp3" },
  { title: "Kya Baat Aa", artist: "Karan Aujla", src: "songs/punjabi/Kya Baat Aa.mp3" },
  { title: "Laembadgini", artist: "Diljit Dosanjh, Veet Baljit", src: "songs/punjabi/Laembadgini.mp3" },
  { title: "Lamberghini", artist: "The Doorbeen, Ragini", src: "songs/punjabi/Lamberghini.mp3" },
  { title: "Laung Laachi", artist: "Mannat Noor", src: "songs/punjabi/Laung Laachi.mp3" },
  { title: "Lehanga", artist: "Jass Manak", src: "songs/punjabi/Lehanga.mp3" },
  { title: "LEHNGA", artist: "Diljit Dosanjh, Neeru Bajwa", src: "songs/punjabi/LEHNGA.mp3" },
  { title: "Levels", artist: "Sidhu Moose Wala, Sunny Malton", src: "songs/punjabi/Levels.mp3" },
  { title: "Ma Belle", artist: "AP Dhillon, Amari", src: "songs/punjabi/Ma Belle.mp3" },
  { title: "Mere Wala Sardar", artist: "Jugraj Sandhu", src: "songs/punjabi/Mere Wala Sardar.mp3" },
  { title: "Mexico Koka", artist: "Karan Aujla", src: "songs/punjabi/Mexico Koka.mp3" },
  { title: "MF GABHRU!", artist: "Karan Aujla, Ikky", src: "songs/punjabi/MF GABHRU!.mp3" },
  { title: "Mill Lo Na", artist: "Guri, Jaani", src: "songs/punjabi/Mill Lo Na.mp3" },
  { title: "Minna Minna", artist: "Garry Sandhu, Manpreet Toor", src: "songs/punjabi/Minna Minna.mp3" },
  { title: "Moon Rise", artist: "Guru Randhawa, Shehnaaz Gill", src: "songs/punjabi/Moon Rise.mp3" },
  { title: "My Prime", artist: "Navaan Sandhu", src: "songs/punjabi/My Prime.mp3" },
  { title: "Na Ja", artist: "Pav Dharia", src: "songs/punjabi/Na Ja.mp3" },
  { title: "Sharara", artist: "Shivjot", src: "songs/punjabi/Sharara.mp3" },
  { title: "Lamborghini", artist: "Khan Bhaini, Shipra Goyal", src: "songs/punjabi/Lamborghini.mp3" },
  { title: "Sun Fer", artist: "Khan Bhaini", src: "songs/punjabi/Sun Fer.mp3" },
  { title: "No Love", artist: "Shubh", src: "songs/punjabi/No Love.mp3" },
  { title: "Obsessed", artist: "Riar Saab, Abhijay Sharma", src: "songs/punjabi/Obsessed.mp3" },
  { title: "Nikle Currant", artist: "Jassi Gill, Neha Kakkar, Sukh-E", src: "songs/punjabi/Nikle Currant.mp3" },
  { title: "On Top", artist: "Karan Aujla", src: "songs/punjabi/On Top.mp3" },
  { title: "PAGAL", artist: "Diljit Dosanjh", src: "songs/punjabi/PAGAL.mp3" },
  { title: "PALAZZO 2", artist: "Kulwinder Billa, Shivjot", src: "songs/punjabi/PALAZZO 2.mp3" },
  { title: "PANJEBAN", artist: "Shivjot, Gurlez Akhtar", src: "songs/punjabi/PANJEBAN.mp3" },
  { title: "PECHA", artist: "Gur Sidhu, Veet Baljit", src: "songs/punjabi/PECHA.mp3" },
  { title: "Prada", artist: "Jass Manak", src: "songs/punjabi/Prada.mp3" },
  { title: "Raule", artist: "Jassa Dhillon, Gurlez Akhtar, Gur Sidhu", src: "songs/punjabi/Raule.mp3" },
  { title: "Rolex", artist: "A Kay", src: "songs/punjabi/Rolex.mp3" },
  { title: "Rubicon Drill", artist: "Laddi Chahal, Parmish Verma, Gurlez Akhtar", src: "songs/punjabi/Rubicon Drill.mp3" },
  { title: "SAFAR", artist: "Juss", src: "songs/punjabi/SAFAR.mp3" },
  { title: "Sajjda", artist: "Ghulam Jugni, Gurvarinder Grewal", src: "songs/punjabi/Sajjda.mp3" },
  { title: "SAKHIYAAN", artist: "Maninder Buttar", src: "songs/punjabi/SAKHIYAAN.mp3" },
  { title: "SCHEDULE", artist: "Tegi Pannu, Manni Sandhu", src: "songs/punjabi/SCHEDULE.mp3" },
  { title: "Baller", artist: "Shubh", src: "songs/punjabi/Baller.mp3" },
  { title: "Cheques", artist: "Shubh", src: "songs/punjabi/Cheques.mp3" },
  { title: "Elevated", artist: "Shubh", src: "songs/punjabi/Elevated.mp3" },
  { title: "Still Rollin", artist: "Shubh", src: "songs/punjabi/Still Rollin.mp3" },
  { title: "Mera Na", artist: "Sidhu Moose Wala, Burna Boy, Steel Banglez", src: "songs/punjabi/Mera Na.mp3" },
  { title: "Sira", artist: "Dilpreet Dhillon, Shipra Goyal", src: "songs/punjabi/Sira.mp3" },
  { title: "Sira E Hou", artist: "Amrit Maan, Nimrat Khaira", src: "songs/punjabi/Sira E Hou.mp3" },
  { title: "SOFTLY", artist: "Karan Aujla, Ikky", src: "songs/punjabi/SOFTLY.mp3" },
  { title: "Spaceship", artist: "AP Dhillon, Shinda Kahlon", src: "songs/punjabi/Spaceship.mp3" },
  { title: "Summer High", artist: "AP Dhillon", src: "songs/punjabi/Summer High.mp3" },
  { title: "Sunakhi", artist: "Kaur B", src: "songs/punjabi/Sunakhi.mp3" },
  { title: "Take It Easy", artist: "Karan Aujla, Ikky", src: "songs/punjabi/Take It Easy.mp3" },
  { title: "Talja", artist: "Jassa Dhillon, Deepak Dhillon, Gur Sidhu", src: "songs/punjabi/Talja.mp3" },
  { title: "Fully Loaded", artist: "Tegi Pannu, Manni Sandhu", src: "songs/punjabi/Fully Loaded.mp3" },
  { title: "Tell Me Honestly", artist: "Ammy Virk, Nimrat Khaira", src: "songs/punjabi/Tell Me Honestly.mp3" },
  { title: "Tenu Pta Nhi Chann Ve", artist: "Gurkaran Malhans", src: "songs/punjabi/Tenu Pta Nhi Chann Ve.mp3" },
  { title: "THAA", artist: "Varinder Brar", src: "songs/punjabi/THAA.mp3" },
  { title: "Top Notch Gabru", artist: "Vicky Dhillon", src: "songs/punjabi/Top Notch Gabru.mp3" },
  { title: "Tu Hi Das De", artist: "Tedi Pagg, Simar Panag, Mickey Singh", src: "songs/punjabi/Tu Hi Das De.mp3" },
  { title: "UNTOUCHABLE", artist: "Tegi Pannu, Manni Sandhu", src: "songs/punjabi/UNTOUCHABLE.mp3" },
  { title: "US", artist: "Sidhu Moose Wala, Raja Kumari", src: "songs/punjabi/US.mp3" },
  { title: "Waalian", artist: "Harnoor", src: "songs/punjabi/Waalian.mp3" },
  { title: "WAVY", artist: "Karan Aujla", src: "songs/punjabi/WAVY.mp3" },
  { title: "We Rollin", artist: "Shubh", src: "songs/punjabi/We Rollin.mp3" },
  { title: "White Brown Black", artist: "Avvy Sra, Karan Aujla, Jaani", src: "songs/punjabi/White Brown Black.mp3" },
  { title: "With You", artist: "AP Dhillon", src: "songs/punjabi/With You.mp3" },
  { title: "Yahama", artist: "Shree Brar", src: "songs/punjabi/Yahama.mp3" },
  { title: "YKWIM", artist: "Karan Aujla, KR$NA", src: "songs/punjabi/YKWIM.mp3" },
  { title: "Illegal Weapon", artist: "Jasmine Sandlas, Garry Sandhu", src: "songs/punjabi/Illegal Weapon.mp3" },
  { title: "Baapu Jatt", artist: "Jassie Gill", src: "songs/punjabi/Baapu Jatt.mp3" },
  { title: "Suit Suit", artist: "Guru Randhawa, Arjun", src: "songs/punjabi/Suit Suit.mp3" },
  { title: "Ishare Tere", artist: "Guru Randhawa, Dhvani Bhanushali", src: "songs/punjabi/Ishare Tere.mp3" }
];
