// 90s songs playlist
const ninetiesSongs = [
  { title: "Aakhir Tumhein Aana Hai", artist: "Udit Narayan, Sapna Mukherjee", src: "songs/90s/Aakhir Tumhein Aana Hai.mp3" },
  { title: "Aap Ka Aana Dil Dhadkana", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Aap Ka Aana Dil Dhadkana.mp3" },
  { title: "Aayegi Har Pal Tujhe Meri Yaad", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Aayegi Har Pal Tujhe Meri Yaad.mp3" },
  { title: "Ab Tere Dil Mein Hum Aa Gaye", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Ab Tere Dil Mein Hum Aa Gaye.mp3" },
  { title: "Andekhi Anjaani", artist: "90s Song", src: "songs/90s/Andekhi Anjaani.mp3" },
  { title: "Bahut Pyaar Karte Hai", artist: "Madhuri_Dixit", src: "songs/90s/Bahut Pyaar Karte Hai.mp3" },
  { title: "Bewaffa Se Waffa", artist: "Lata Mangeshkar", src: "songs/90s/Bewaffa Se Waffa.mp3" },
  { title: "Bholi Si Surat", artist: "Lata Mangeshkar, Udit Narayan", src: "songs/90s/Bholi Si Surat.mp3" },
  { title: "Chhodo mujhe Jane do", artist: "90s Song", src: "songs/90s/Chhodo mujhe Jane do.mp3" },
  { title: "Chod Ke Na Jaa O Piya", artist: "Alka Yagnik", src: "songs/90s/Chod Ke Na Jaa O Piya.mp3" },
  { title: "Dil Mein Dard Sa Jaga Hai", artist: "Udit Narayan, Alka Yagnik", src: "songs/90s/Dil Mein Dard Sa Jaga Hai.mp3" },
  { title: "Dil Ne Yeh Kaha", artist: "Alka_Y,_Kumar_S,_Udit_N", src: "songs/90s/Dil Ne Yeh Kaha.mp3" },
  { title: "Dil pe chalai churiya", artist: "90s Song", src: "songs/90s/Dil pe chalai churiya.mp3" },
  { title: "Do Pal", artist: "Lata Mangeshkar, Sonu Nigam", src: "songs/90s/Do Pal.mp3" },
  { title: "Ek Dil Hai", artist: "90s Song", src: "songs/90s/Ek Dil Hai.mp3" },
  { title: "Ek Din Aap", artist: "90s Song", src: "songs/90s/Ek Din Aap.mp3" },
  { title: "Ek Mulaqat Zaroori Hai Sanam", artist: "Ameen_Sabri,_Fareed_Sabri", src: "songs/90s/Ek Mulaqat Zaroori Hai Sanam.mp3" },
  { title: "Pehle Kabhi Na Mera Haal", artist: "90s Song", src: "songs/90s/Pehle Kabhi Na Mera Haal.mp3" },
  { title: "Haseeno Ko Aate Hain Kya Kya Bahane", artist: "Udit Narayan, Alka Yagnik", src: "songs/90s/Haseeno Ko Aate Hain Kya Kya Bahane.mp3" },
  { title: "Ho Gaya Hai Tujhko Toh Pyar Sajna", artist: "90s Song", src: "songs/90s/Ho Gaya Hai Tujhko Toh Pyar Sajna.mp3" },
  { title: "Humko Humise Chura Lo", artist: "90s Song", src: "songs/90s/Humko Humise Chura Lo.mp3" },
  { title: "Humko Sirf Tumse Pyar Hai", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Humko Sirf Tumse Pyar Hai.mp3" },
  { title: "Hum Unse Mohabbat Karke", artist: "Kumar Sanu, Sadhana Sargam", src: "songs/90s/Hum Unse Mohabbat Karke.mp3" },
  { title: "Ghunghat Mein Chand Hoga", artist: "Kumar Sanu, Sadhana Sargam", src: "songs/90s/Ghunghat Mein Chand Hoga.mp3" },
  { title: "Ishq Mein Tumhein Kya Batayein", artist: "Sonu Nigam", src: "songs/90s/Ishq Mein Tumhein Kya Batayein.mp3" },
  { title: "Is Kadar", artist: "Artist not listed", src: "songs/90s/Is Kadar.mp3" },
  { title: "Is Pyar Se Meri Taraf Na Dekho", artist: "Kumar Sanu", src: "songs/90s/Is Pyar Se Meri Taraf Na Dekho.mp3" },
  { title: "Itna Main Chahoon Tujhe Koi Kisi Ko Na Chahe", artist: "Udit Narayan", src: "songs/90s/Itna Main Chahoon Tujhe Koi Kisi Ko Na Chahe.mp3" },
  { title: "Jaadu Teri Nazar", artist: "Udit Narayan", src: "songs/90s/Jaadu Teri Nazar.mp3" },
  { title: "Jab Haal E Dil Tumse Kehne Ko", artist: "Alka Yagnik", src: "songs/90s/Jab Haal E Dil Tumse Kehne Ko.mp3" },
  { title: "Janam Janam Jo Saath", artist: "Udit Narayan, Alka Yagnik", src: "songs/90s/Janam Janam Jo Saath.mp3" },
  { title: "Kya Tumhe Pata Hai", artist: "90s Song", src: "songs/90s/Kya Tumhe Pata Hai.mp3" },
  { title: "Hamein Tumse Hua Hai Pyar", artist: "Alka Yagnik, Udit Narayan", src: "songs/90s/Hamein Tumse Hua Hai Pyar.mp3" },
  { title: "Main Agar Kahoon", artist: "Sonu Nigam", src: "songs/90s/Main Agar Kahoon.mp3" },
  { title: "Tu Meri Zindagi Hai", artist: "Kumar Sanu, Anuradha Paudwal", src: "songs/90s/Tu Meri Zindagi Hai.mp3" },
  { title: "Main Chahta Hoon Tujhko", artist: "Abhijeet, Alka Yagnik", src: "songs/90s/Main Chahta Hoon Tujhko.mp3" },
  { title: "Main Duniya Bhula Doonga", artist: "Kumar Sanu", src: "songs/90s/Main Duniya Bhula Doonga.mp3" },
  { title: "Mere Khwabon Mein", artist: "Lata Mangeshkar", src: "songs/90s/Mere Khwabon Mein.mp3" },
  { title: "Mitwa Bhool Na Jana", artist: "Udit Narayan, Anuradha Paudwal", src: "songs/90s/Mitwa Bhool Na Jana.mp3" },
  { title: "Meri Mehbooba", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Meri Mehbooba.mp3" },
  { title: "Mile Tum Se Bichhad Ke Hum", artist: "90s Song", src: "songs/90s/Mile Tum Se Bichhad Ke Hum.mp3" },
  { title: "Nazrein Mili Dil Dhadka", artist: "Alka Yagnik, Udit Narayan", src: "songs/90s/Nazrein Mili Dil Dhadka.mp3" },
  { title: "Mohabbat Se Zyada", artist: "Udit Narayan, Shreya Ghoshal", src: "songs/90s/Mohabbat Se Zyada.mp3" },
  { title: "Mubarak Ho Tumko Ye Shaadi Tumhari", artist: "Udit_Narayan", src: "songs/90s/Mubarak Ho Tumko Ye Shaadi Tumhari.mp3" },
  { title: "Mujhko Yaad Sataye Teri", artist: "Himesh Reshammiya", src: "songs/90s/Mujhko Yaad Sataye Teri.mp3" },
  { title: "Mujhse Mohabbat Ka Izhaar", artist: "90s Song", src: "songs/90s/Mujhse Mohabbat Ka Izhaar.mp3" },
  { title: "Paas Woh Aane Lage", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Paas Woh Aane Lage.mp3" },
  { title: "Pehle To Kabhi Kabhi Gham Tha", artist: "Altaf Raja", src: "songs/90s/Pehle To Kabhi Kabhi Gham Tha.mp3" },
  { title: "Pehli Pehli Baar Mohabbat Ki Hai", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Pehli Pehli Baar Mohabbat Ki Hai.mp3" },
  { title: "Pyaar Ki Ek Kahani", artist: "Sonu Nigam", src: "songs/90s/Pyaar Ki Ek Kahani.mp3" },
  { title: "Raah Mein Unse Mulaqat", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Raah Mein Unse Mulaqat.mp3" },
  { title: "Shaam Hai Dhuan", artist: "Diljale___Ajay_Devgan", src: "songs/90s/Shaam Hai Dhuan.mp3" },
  { title: "Sochta Houn", artist: "90s Song", src: "songs/90s/Sochta Houn.mp3" },
  { title: "Suraj Hua Maddham", artist: "Alka Yagnik, Sonu Nigam", src: "songs/90s/Suraj Hua Maddham.mp3" },
  { title: "Teri Chunariya Dil Le Gayi", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Teri Chunariya Dil Le Gayi.mp3" },
  { title: "To Chalun", artist: "90s Song", src: "songs/90s/To Chalun.mp3" },
  { title: "Tumhare Siva", artist: "Udit Narayan, Anuradha Paudwal", src: "songs/90s/Tumhare Siva.mp3" },
  { title: "Tumhein Dekhe Meri", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Tumhein Dekhe Meri.mp3" },
  { title: "Tum Dil Ki Dhadkan Mein", artist: "Suniel_Shetty_Shilpa_Shetty", src: "songs/90s/Tum Dil Ki Dhadkan Mein.mp3" },
  { title: "Wadiye Ishq Se Aaya Hai Mera Shahzada", artist: "90s Song", src: "songs/90s/Wadiye Ishq Se Aaya Hai Mera Shahzada.mp3" },
  { title: "Woh Kisi Aur Se", artist: "_Agam_Kumar_Sonu_Nigam_", src: "songs/90s/Woh Kisi Aur Se.mp3" },
  { title: "Woh Ladki Bohot Yaad Aati Hai", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Woh Ladki Bohot Yaad Aati Hai.mp3" },
  { title: "Yeh Dua Hai Meri", artist: "90s Song", src: "songs/90s/Yeh Dua Hai Meri.mp3" },
  { title: "Yeh Pyar Ho Na Khatam", artist: "Yasser_Desai", src: "songs/90s/Yeh Pyar Ho Na Khatam.mp3" },
  { title: "Do Lafzo Mein", artist: "_Aishwarya_Rai,_Abhishek_Bacchan", src: "songs/90s/Do Lafzo Mein.mp3" },
  { title: "Jaan-E-Zigar Jaaneman", artist: "_Rahul_Roy,_Anu_Agarwal", src: "songs/90s/Jaan-E-Zigar Jaaneman.mp3" },
  { title: "Is Tarah Aashiqui Ka", artist: "Kumar Sanu", src: "songs/90s/Is Tarah Aashiqui Ka Asar Chhod Jaunga.mp3" },
  { title: "Kasam Se Kasam Se", artist: "Udit Narayan_Alka Yagnik", src: "songs/90s/Kasam Se Kasam Se.mp3" },
  { title: "Kyun Ki Itna Pyaar", artist: "90s Song", src: "songs/90s/Kyun Ki Itna Pyaar.mp3" },
  { title: "Chori Chori Dil Tera Churayenge", artist: "Kumar Sanu", src: "songs/90s/Chori Chori Dil Tera Churayenge.mp3" },
  { title: "Jo Bhi Kasmein", artist: "Udit Narayan_Alka Yagnik", src: "songs/90s/Jo Bhi Kasmein.mp3" },
  { title: "Tu Pyar Hai Kisi Aur Ka", artist: "90s Song", src: "songs/90s/Tu Pyar Hai Kisi Aur Ka.mp3" },
  { title: "Bahut Jatate Ho Chah Humse", artist: "90s Song", src: "songs/90s/Bahut Jatate Ho Chah Humse.mp3" },
  { title: "Mera Dil Jis Dil Pe Fida Hai", artist: "Udit Narayan", src: "songs/90s/Mera Dil Jis Dil Pe Fida Hai.mp3" },
  { title: "Main Ishq Uska", artist: "90s Song", src: "songs/90s/Main Ishq Uska.mp3" },
  { title: "Mauka Milega To Hum", artist: "90s Song", src: "songs/90s/Mauka Milega To Hum.mp3" },
  { title: "Shaam Bhi Khoob Hai", artist: "90s Song", src: "songs/90s/Shaam Bhi Khoob Hai.mp3" },
  { title: "Hum Nahi", artist: "90s Song", src: "songs/90s/Hum Nahi.mp3" },
  { title: "Acche Lagte Ho", artist: "Udit Narayan", src: "songs/90s/Acche lagte ho.mp3" },
  { title: "Aankhein Khuli", artist: "Lata Mangeshkar_Udit Narayan", src: "songs/90s/Aankhein Khuli.mp3" },
  { title: "Chaaha Hai Tujhko", artist: "Udit Narayan_Anuradha Paudwal", src: "songs/90s/Chaaha Hai Tujhko.mp3" },
  { title: "Tum Se Achcha Kaun Hai", artist: "Nakul Kapoor", src: "songs/90s/Tum Se Achcha Kaun Hai.mp3" },
  { title: "Jugni Jugni", artist: "Anu Malik", src: "songs/90s/Jugni Jugni.mp3" },
  { title: "Hadh Kardi Aapne", artist: "90s Song", src: "songs/90s/Hadh Kardi Aapne.mp3" },
  { title: "Hum Tere Shahar Mein Aaye Hain", artist: "90s Song", src: "songs/90s/Hum Tere Shahar Mein Aaye Hain.mp3" },
  { title: "Kahin Mujhe Pyar Hua Toh Nahi Hai", artist: "Alka Yagnik_Kumar Sanu", src: "songs/90s/Kahin Mujhe Pyar Hua Toh Nahi Hai.mp3" },
  { title: "Kasam Khake Kaho", artist: "Alka Yagnik_Kumar Sanu", src: "songs/90s/Kasam Khake Kaho.mp3" },
  { title: "Tu Na Ja Mere Badshah", artist: "Mohd Aziz_Alka Yagnik", src: "songs/90s/Tu Na Ja Mere Badshah.mp3" },
  { title: "Kisi Din Banoongi Main Raja Ki Rani", artist: "Madhuri Dixit_Sanjay Kapoor", src: "songs/90s/Kisi Din Banoongi Main Raja Ki Rani.mp3" },
  { title: "Kiya Kiya", artist: "Akshay Kumar_Katrina Kaif", src: "songs/90s/Kiya Kiya.mp3" },
  { title: "Mera Sanam Sabse Pyara Hai", artist: "Asha Bhosle_Kumar Sanu", src: "songs/90s/Mera Sanam Sabse Pyara Hai.mp3" },
  { title: "Mohabbat Dil Ka Sakoon", artist: "Kumar Sanu_Alka Yagnik_Udit Narayan", src: "songs/90s/Mohabbat Dil Ka Sakoon Hai Aitbaar.mp3" },
  { title: "Na Milo Kahin Pyar", artist: "Sonu Nigam_Kavita Krishnamurthy", src: "songs/90s/Na Milo Kahin Pyar.mp3" },
  { title: "Pardesi Pardesi", artist: "Udit Narayan_Alka Yagnik", src: "songs/90s/Pardesi Pardesi.mp3" },
  { title: "Tu Cheez Badi Hai Mast", artist: "Akshay Kumar_Raveena Tandon", src: "songs/90s/Tu Cheez Badi Hai Mast.mp3" },
  { title: "Tumse Milne Ki Tamanna Hai", artist: "Salman Khan_Madhuri", src: "songs/90s/Tumse Milne Ki Tamanna Hai.mp3" },
  { title: "Tumse Milne Ko Dil Karta Hai", artist: "Alka Yagnik_Kumar Sanu", src: "songs/90s/Tumse Milne Ko Dil Karta Hai.mp3" },
  { title: "Kitna Haseen Chehra", artist: "Kumar Sanu", src: "songs/90s/Kitna Haseen Chehra.mp3" },
  { title: "Tu Dharti Pe", artist: "Alka Yagnik_Kumar Sanu", src: "songs/90s/Tu Dharti Pe Chaahe Jahan Bhi Rahegi.mp3" },
  { title: "Dil Cheez Tujhe Dedi", artist: "Ankit Tiwari_Arijit Singh", src: "songs/90s/Dil Cheez Tujhe Dedi.mp3" },
  { title: "Humen Tumse Pyar Kitna", artist: "Rajesh Khanna_Hema Malini", src: "songs/90s/Humen Tumse Pyar Kitna.mp3" },
  { title: "Aankh Milate Darr Lagta Hai", artist: "Raja", src: "songs/90s/Aankh Milate Darr Lagta Hai.mp3" },
  { title: "Akhiyaan Milaoon Kabhi", artist: "Raja", src: "songs/90s/Akhiyaan Milaoon Kabhi.mp3" },
  { title: "Jaa Sajna Tujhko Bhula", artist: "Raja", src: "songs/90s/Jaa Sajna Tujhko Bhula.mp3" },
  { title: "Jhuki Jhuki Nazar Teri Kamaal", artist: "Alka Yagnik_Udit Narayan", src: "songs/90s/Jhuki Jhuki Nazar Teri Kamaal.mp3" },
  { title: "Paa Liya Hain Pyar Tera", artist: "Alka Yagnik_Udit Narayan", src: "songs/90s/Paa Liya Hain Pyar Tera.mp3" },
  { title: "Phool Maangu Na Bahaar Maangu", artist: "Raja", src: "songs/90s/Phool Maangu Na Bahaar Maangu.mp3" },
  { title: "Duniya Haseeno Ka Mela", artist: "Raja", src: "songs/90s/Duniya Haseeno Ka Mela.mp3" },
];
