// 90s songs playlist
const ninetiesSongs = [
  { title: "Aakhir Tumhein Aana Hai", artist: "Udit Narayan, Sapna Mukherjee", src: "songs/90s/Aakhir Tumhein Aana Hai.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Aap Ka Aana Dil Dhadkana", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Aap Ka Aana Dil Dhadkana.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Aayegi Har Pal Tujhe Meri Yaad", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Aayegi Har Pal Tujhe Meri Yaad.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Ab Tere Dil Mein Hum Aa Gaye", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Ab Tere Dil Mein Hum Aa Gaye.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Andekhi Anjaani", artist: "90s Song", src: "songs/90s/Andekhi Anjaani.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Bahut Pyaar Karte Hai", artist: "Madhuri_Dixit", src: "songs/90s/Bahut Pyaar Karte Hai.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Bewaffa Se Waffa", artist: "Lata Mangeshkar", src: "songs/90s/Bewaffa Se Waffa.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Bholi Si Surat", artist: "Lata Mangeshkar, Udit Narayan", src: "songs/90s/Bholi Si Surat.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Chhodo mujhe Jane do", artist: "90s Song", src: "songs/90s/Chhodo mujhe Jane do.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Chod Ke Na Jaa O Piya", artist: "Alka Yagnik", src: "songs/90s/Chod Ke Na Jaa O Piya.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Dil Ka Jo Haal Hai", artist: "Shreya Ghoshal, Abhijeet Bhattacharya", src: "songs/90s/Dil Ka Jo Haal Hai.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Dil Mein Dard Sa Jaga Hai", artist: "Udit Narayan, Alka Yagnik", src: "songs/90s/Dil Mein Dard Sa Jaga Hai.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Dil Ne Yeh Kaha", artist: "Alka_Y,_Kumar_S,_Udit_N", src: "songs/90s/Dil Ne Yeh Kaha.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Dil pe chalai churiya", artist: "90s Song", src: "songs/90s/Dil pe chalai churiya.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Do Pal", artist: "Lata Mangeshkar, Sonu Nigam", src: "songs/90s/Do Pal.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Ek Dil Hai", artist: "90s Song", src: "songs/90s/Ek Dil Hai.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Ek Din Aap", artist: "90s Song", src: "songs/90s/Ek Din Aap.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Ek Mulaqat Zaroori Hai Sanam", artist: "Ameen_Sabri,_Fareed_Sabri", src: "songs/90s/Ek Mulaqat Zaroori Hai Sanam.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Pehle Kabhi Na Mera Haal", artist: "90s Song", src: "songs/90s/Pehle Kabhi Na Mera Haal.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Haseeno Ko Aate Hain Kya Kya Bahane", artist: "Udit Narayan, Alka Yagnik", src: "songs/90s/Haseeno Ko Aate Hain Kya Kya Bahane.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Ho Gaya Hai Tujhko Toh Pyar Sajna", artist: "90s Song", src: "songs/90s/Ho Gaya Hai Tujhko Toh Pyar Sajna.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Humko Humise Chura Lo", artist: "90s Song", src: "Humko Humise Chura Lo.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Humko Sirf Tumse Pyar Hai", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Humko Sirf Tumse Pyar Hai.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Hum Unse Mohabbat Karke", artist: "Kumar Sanu, Sadhana Sargam", src: "songs/90s/Hum Unse Mohabbat Karke.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Ishq Mein Tumhein Kya Batayein", artist: "Sonu Nigam", src: "songs/90s/Ishq Mein Tumhein Kya Batayein.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Is Pyar Se Meri Taraf Na Dekho", artist: "Kumar Sanu", src: "songs/90s/Is Pyar Se Meri Taraf Na Dekho.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Itna Main Chahoon Tujhe Koi Kisi Ko Na Chahe", artist: "Udit Narayan", src: "songs/90s/Itna Main Chahoon Tujhe Koi Kisi Ko Na Chahe.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Jaadu Teri Nazar", artist: "Udit Narayan", src: "songs/90s/Jaadu Teri Nazar.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Jab Haal E Dil Tumse Kehne Ko", artist: "Alka Yagnik", src: "songs/90s/Jab Haal E Dil Tumse Kehne Ko.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Janam Janam Jo Saath", artist: "Udit Narayan, Alka Yagnik", src: "songs/90s/Janam Janam Jo Saath.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Kya Tumhe Pata Hai", artist: "90s Song", src: "songs/90s/Kya Tumhe Pata Hai.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Hamein Tumse Hua Hai Pyar", artist: "Alka Yagnik, Udit Narayan", src: "songs/90s/Hamein Tumse Hua Hai Pyar.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Main Agar Kahoon", artist: "Sonu Nigam", src: "songs/90s/Main Agar Kahoon.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Tu Meri Zindagi Hai", artist: "Kumar Sanu, Anuradha Paudwal", src: "songs/90s/Tu Meri Zindagi Hai.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Main Chahta Hoon Tujhko", artist: "Abhijeet, Alka Yagnik", src: "songs/90s/Main Chahta Hoon Tujhko.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Main Duniya Bhula Doonga", artist: "Kumar Sanu", src: "songs/90s/Main Duniya Bhula Doonga.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Mere Khwabon Mein", artist: "Lata Mangeshkar", src: "songs/90s/Mere Khwabon Mein.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Meri Mehbooba", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Meri Mehbooba.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Mile Tum Se Bichhad Ke Hum", artist: "90s Song", src: "songs/90s/Mile Tum Se Bichhad Ke Hum.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Mohabbat Se Zyada", artist: "Udit Narayan, Shreya Ghoshal", src: "songs/90s/Mohabbat Se Zyada.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Mubarak Ho Tumko Ye Shaadi Tumhari", artist: "Udit_Narayan", src: "songs/90s/Mubarak Ho Tumko Ye Shaadi Tumhari.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Mujhko Yaad Sataye Teri", artist: "Himesh Reshammiya", src: "songs/90s/Mujhko Yaad Sataye Teri.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Mujhse Mohabbat Ka Izhaar", artist: "90s Song", src: "songs/90s/Mujhse Mohabbat Ka Izhaar.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Paas Woh Aane Lage", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Paas Woh Aane Lage.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Pehle To Kabhi Kabhi Gham Tha", artist: "Altaf Raja", src: "songs/90s/Pehle To Kabhi Kabhi Gham Tha.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Pehli Pehli Baar Mohabbat Ki Hai", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Pehli Pehli Baar Mohabbat Ki Hai.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Pyaar Ki Ek Kahani", artist: "Sonu Nigam", src: "songs/90s/Pyaar Ki Ek Kahani.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Raah Mein Unse Mulaqat", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Raah Mein Unse Mulaqat.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Shaam Hai Dhuan", artist: "Diljale___Ajay_Devgan", src: "songs/90s/Shaam Hai Dhuan.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Sochta Houn", artist: "90s Song", src: "songs/90s/Sochta Houn.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Suraj Hua Maddham", artist: "Alka Yagnik, Sonu Nigam", src: "songs/90s/Suraj Hua Maddham.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Teri Chunariya Dil Le Gayi", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Teri Chunariya Dil Le Gayi.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "To Chalun", artist: "90s Song", src: "songs/90s/To Chalun.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Tumhare Siva", artist: "Udit Narayan, Anuradha Paudwal", src: "songs/90s/Tumhare Siva.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Tumhein Dekhe Meri", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Tumhein Dekhe Meri.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Tum Dil Ki Dhadkan Mein", artist: "Suniel_Shetty_Shilpa_Shetty", src: "songs/90s/Tum Dil Ki Dhadkan Mein.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Wadiye Ishq Se Aaya Hai Mera Shahzada", artist: "90s Song", src: "Wadiye Ishq Se Aaya Hai Mera Shahzada.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Woh Kisi Aur Se", artist: "_Agam_Kumar_Sonu_Nigam_", src: "songs/90s/Woh_Kisi_Aur_Se_Full_Video___Phir_Bewafai___Agam_Kumar_Nigam___T-Series(256k).mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Woh Ladki Bohot Yaad Aati Hai", artist: "Alka Yagnik, Kumar Sanu", src: "songs/90s/Woh Ladki Bohot Yaad Aati Hai.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Yeh Dua Hai Meri", artist: "90s Song", src: "songs/90s/Yeh Dua Hai Meri.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Yeh Pyar Ho Na Khatam", artist: "Yasser_Desai", src: "songs/90s/Yeh Pyar Ho Na Khatam.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Do Lafzo Mein", artist: "_Aishwarya_Rai,_Abhishek_Bacchan", src: "songs/90s/Do Lafzo Mein.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Jaan-E-Zigar Jaaneman", artist: "_Rahul_Roy,_Anu_Agarwal", src: "songs/90s/Jaan-E-Zigar Jaaneman.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Is Tarah Aashiqui Ka Asar Chhod Jaunga", artist: "Kumar Sanu", src: "songs/90s/Is Tarah Aashiqui Ka Asar Chhod Jaunga.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Kasam Se Kasam Se", artist: "Udit Narayan_Alka Yagnik", src: "songs/90s/कसम_से_कसम_से_-_जानवर_गीत___एचडी___-_अक्षय_कुमार_-_करिश्मा_कपूर_-_उदित_नारायण_-_अलका_याग्निक(256k).mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Kyun Ki Itna Pyaar", artist: "90s Song", src: "songs/90s/Kyun Ki Itna Pyaar.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Chori Chori Dil Tera Churayenge", artist: "Kumar Sanu", src: "songs/90s/Chori Chori Dil Tera Churayenge.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Jo Bhi Kasmein", artist: "Udit Narayan_Alka Yagnik", src: "songs/90s/जो_भी_कसमें_-_राज___बिपाशा_बसु_और_डीनो_मोरिया___उदित_नारायण_और_अलका_याग्निक(256k).mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Tu Pyar Hai Kisi Aur Ka", artist: "90s Song", src: "songs/90s/Tu Pyar Hai Kisi Aur Ka.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Bahut Jatate Ho Chah Humse", artist: "90s Song", src: "songs/90s/Bahut Jatate Ho Chah Humse.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Mera Dil Jis Dil Pe Fida Hai", artist: "Udit Narayan", src: "songs/90s/Mera Dil Jis Dil Pe Fida Hai.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Main Ishq Uska", artist: "90s Song", src: "songs/90s/Main Ishq Uska.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Mauka Milega To Hum", artist: "90s Song", src: "songs/90s/Mauka Milega To Hum.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Shaam Bhi Khoob Hai", artist: "90s Song", src: "songs/90s/Shaam Bhi Khoob Hai.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Hum Nahi", artist: "90s Song", src: "songs/90s/Hum Nahi.mp3", cover: 'images/90s/90s songs.jpg' },
  { title: "Acche Lagte Ho", artist: "Udit Narayan", src: "songs/90s/Acche lagte ho.mp3", cover: "images/90s/90s songs.jpg" },

];



